### ISSUE TITLE
Pick a generative testing library

### ISSUE THREAD

**Issue by scotttrinh** [scotttrinh/tinydot#3]
Both for testing the code and for providing generators for the specs. My feeling is that we should go with [`testcheck-js`](https://github.com/leebyron/testcheck-js) since it's based on ClojureScript's test check implementation, so it should be the easiest to keep parity with `core.spec` and it's features.

I'll go ahead and get a PR going for this.

**Comment by busypeoples** [comment]
Excellent.

**Comment by scotttrinh** [comment]
Closed by 28f04fc
